### ISSUE TITLE
[MENFORCER-117] Custom Packaging with executions fails with ArrayIndexOutOfBoundsException in RequirePluginVersions.java:702

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-enforcer#404]
**[Barrie Treloar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baerrach)** opened **[MENFORCER-117](https://issues.apache.org/jira/browse/MENFORCER-117?redirect=false)** and commented

The pde-maven-plugin causes enforcer to NPE.

I've attached an IT pom.xml.
I haven't had time to investigate this any further than to get the IT to fail the same as my real build.

```
  <packaging>zip</packaging>

  <build>
    <plugins>
      <plugin>    
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>pde-maven-plugin</artifactId>
        <version>1.0-alpha-1</version>
        <extensions>true</extensions>
        <configuration>
           <buildProperties>
             <pdeProductFilename>example.product</pdeProductFilename>
           </buildProperties>
        </configuration>
        <!-- Also bind to mvn clean -->
        <executions>
          <execution>
            <id>clean-pde</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>        
      </plugin>
...
```

---

**Affects:** 1.0.1

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12716467/pom.xml) (_2.91 kB_)

**Comment by jira-importer** [comment]
**[Barrie Treloar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baerrach)** commented

Exception raised:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.2-SNAPSHOT:enforce (test) on project pluginWithExtensions: Execution test of goal org.apache.maven.plugins:maven-enforcer-plugin:1.2-SNAPSHOT:enforce failed: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.2-SNAPSHOT:enforce (test) on project pluginWithExtensions: Execution test of goal org.apache.maven.plugins:maven-enforcer-plugin:1.2-SNAPSHOT:enforce failed: 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution test of goal org.apache.maven.plugins:maven-enforcer-plugin:1.2-SNAPSHOT:enforce failed: 1
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.maven.plugins.enforcer.RequirePluginVersions.getAllPlugins(RequirePluginVersions.java:708)
	at org.apache.maven.plugins.enforcer.RequirePluginVersions.getBoundPlugins(RequirePluginVersions.java:570)
	at org.apache.maven.plugins.enforcer.RequirePluginVersions.execute(RequirePluginVersions.java:201)
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:190)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)

```

**Comment by jira-importer** [comment]
**[Barrie Treloar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baerrach)** commented

Investigation shows:
Line 708 (was 702 prior to the start of hacking)

```
plugin.setArtifactId( tokens[1] );
```

Dumping out what tokens is and some surrounding variables:

```
[ERROR] entry =clean=org.apache.maven.plugins:maven-clean-plugin:2.4.1:clean
[ERROR] value =org.apache.maven.plugins:maven-clean-plugin:2.4.1:clean
[ERROR] tokens =[org.apache.maven.plugins, maven-clean-plugin, 2.4.1, clean]
[ERROR] entry =install=org.apache.maven.plugins:maven-install-plugin:install
[ERROR] value =org.apache.maven.plugins:maven-install-plugin:install
[ERROR] tokens =[org.apache.maven.plugins, maven-install-plugin, install]
[ERROR] entry =generate-sources=
```

Likewise for the other test project being added

```
[ERROR] entry =integration-test=
[ERROR] value =
[ERROR] tokens =[]
```

So RequirePluginVersions needs to handle empty lifecycles.

**Comment by jira-importer** [comment]
**[Barrie Treloar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baerrach)** commented

Did not take into account that lifecycles may have no plugins bound to them.
Also the formatting of some of the strings coming back included whitespace/newlines.
