### ISSUE TITLE
[MENFORCER-326] Log output

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-enforcer#448]
**[Thomas Nikolay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tnikolay)** opened **[MENFORCER-326](https://issues.apache.org/jira/browse/MENFORCER-326?redirect=false)** and commented

Please improve the output - because it is not clear which rule execution raise an error

 

```
INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-plugin-versions) @ bhs-ws-interface ---
[INFO] Adding ignore: module-info
[INFO] Adding ignore: META-INF/versions/*/module-info
[INFO] Adding ignore: org.jaxen.*
[INFO] Adding ignore: org.xml.sax.*
[INFO] Adding ignore: com.l2fprod.common.*
[INFO] Adding ignore: net.sf.json.*
[INFO] Adding ignore: com.eviware.soapui.analytics.providers.*
[INFO] Adding ignore: net.sf.ezmorph.*
[INFO] Adding ignore: org.apache.xmlbeans.*
[INFO] Adding ignore: schemaorg_apache_xmlbeans.system.*
[INFO] Adding ignore: org.apache.commons.httpclient.*
[INFO] Adding ignore: org.w3c.dom.*
[INFO] Adding ignore: org.aopalliance.*
[INFO] Adding ignorable dependency: null:jaxb-core:null
[INFO] Adding ignore: com.sun.istack.*
[INFO] Adding ignorable dependency: null:xml-apis:null
[INFO] Adding ignore: org.w3c.dom.*
[INFO] Adding ignore: javax.xml.*
[INFO] Adding ignorable dependency: null:cxf-bundle-jaxrs:null
[INFO] Adding ignore: org.apache.cxf.*
[INFO] Adding ignorable dependency: null:asm:null
[INFO] Adding ignore: org.objectweb.*
[INFO] Adding ignorable dependency: null:shtrihjavapos:null
[INFO] Adding ignore: *
[INFO] Adding ignorable dependency: null:commons-collections:null
[INFO] Adding ignore: org.apache.commons.collections.*
[INFO] Adding ignorable dependency: null:commons-beanutils:null
[INFO] Adding ignore: org.apache.commons.beanutils.*
[INFO] Adding ignorable dependency: null:lib-common-utils:null
[INFO] Adding ignore: org.springframework.beans.CachedIntrospectionResults
[INFO] Adding ignorable dependency: null:bcprov-jdk15on:null
[INFO] Adding ignore: org.bouncycastle.*
[INFO] Adding ignorable dependency: null:bcprov-ext-jdk15on:null
[INFO] Adding ignore: org.bouncycastle.*
[INFO] Adding ignorable dependency: null:geronimo-jaxws_2.2_spec:null
[INFO] Adding ignore: org.apache.geronimo.osgi.locator.*
[INFO] Adding ignorable dependency: null:org.eclipse.jdt.core:null
[INFO] Adding ignore: org.eclipse.jdt.*
[INFO] Adding ignorable dependency: null:mod-reporting-if:null
[INFO] Adding ignorable dependency: null:namespace:null
[INFO] Adding ignore: javax.xml.*
[INFO] Adding ignorable dependency: null:mod-md-master-data-api:null
[INFO] Adding ignorable dependency: null:stax-api:null
[INFO] Adding ignore: javax.xml.stream.*
[INFO] Adding ignorable dependency: null:barcode4j-light:null
[INFO] Adding ignore: *
[INFO] Adding ignorable dependency: null:mod-data-provider-server:null
[INFO] Adding ignore: com.sap.*
[INFO] Adding ignorable dependency: null:commons-logging-api:null
[INFO] Adding ignore: org.apache.commons.logging.*
[INFO] Adding ignorable dependency: org.apache.derby:derby:null
[INFO] Adding ignore: org.apache.derby.*
[INFO] Adding ignorable dependency: org.apache.xmlgraphics:batik-ext:null
[INFO] Adding ignore: org.w3c.*
[INFO] Adding ignorable dependency: jfree:jcommon:null
[INFO] Adding ignore: com.keypoint.PngEncoder
[INFO] Adding ignorable dependency: aopalliance:aopalliance:null
[INFO] Adding ignore: org.aopalliance*
[INFO] Adding ignorable dependency: org.apache.geronimo.specs:geronimo-javamail_1.4_spec:null
[INFO] Adding ignore: javax.mail.*
[INFO] Adding ignorable dependency: org.mortbay.jetty:servlet-api:null
[INFO] Adding ignore: javax.servlet.*
[INFO] Adding ignorable dependency: com.google.code.findbugs:jsr305:null
[INFO] Adding ignore: javax.annotation.*

[WARNING] Could not find org.powermock:powermock-reflect:jar:1.7.3:test at null
[WARNING] Could not find org.powermock:powermock-module-junit4-common:jar:1.7.3:test at null
[WARNING] Could not find org.apache.cxf:cxf-rt-frontend-jaxrs:jar:2.7.18:compile at null
[WARNING] Could not find org.codehaus.jackson:jackson-mapper-asl:jar:1.9.11:compile at null
[WARNING] Could not find org.apache.cxf:cxf-rt-frontend-jaxws:jar:2.7.18:compile at null
[WARNING] Could not find org.powermock:powermock-module-junit4-legacy:jar:1.7.3:test at null
[WARNING] Could not find org.codehaus.jackson:jackson-xc:jar:1.9.11:compile at null
[WARNING] Could not find org.powermock:powermock-api-mockito:jar:1.7.3:test at null
[WARNING] Could not find org.mockito:mockito-core:jar:1.10.19:test at null
[WARNING] Could not find org.apache.derby:derby:jar:10.10.2.0:test at null
[WARNING] Could not find com.smartbear.soapui:soapui-maven-plugin:jar:5.2.1:test at null
[WARNING] Could not find org.powermock:powermock-api-support:jar:1.7.3:test at null
[WARNING] Could not find org.powermock:powermock-classloading-base:jar:1.7.3:test at null
[WARNING] Could not find com.fasterxml.jackson.core:jackson-databind:jar:2.6.7:compile at null
[WARNING] Could not find org.powermock:powermock-module-junit4:jar:1.7.3:test at null
[WARNING] Could not find junit:junit:jar:4.12:test at null
[WARNING] Could not find org.codehaus.jackson:jackson-jaxrs:jar:1.9.11:compile at null
[WARNING] Could not find org.powermock:powermock-core:jar:1.7.3:test at null
...
...
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce-plugin-versions) on project bhs-ws-interface: Execution enforce-plugin-versions of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve following dependencies: [maven-plugins:maven-cobertura-plugin:plugin:1.3 (test), maven-plugins:maven-findbugs-plugin:plugin:1.3.1 (test)]: Could not resolve dependencies for project *:1.10.0-b01-SNAPSHOT: The following artifacts could not be resolved: maven-plugins:maven-cobertura-plugin:plugin:1.3, maven-plugins:maven-findbugs-plugin:plugin:1.3.1: Failure to find maven-plugins:maven-cobertura-plugin:plugin:1.3 in * was cached in the local repository, resolution will not be reattempted until the update interval of nexus.public has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce-plugin-versions) on project bhs-ws-interface: Execution enforce-plugin-versions of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve following dependencies: [maven-plugins:maven-cobertura-plugin:plugin:1.3 (test), maven-plugins:maven-findbugs-plugin:plugin:1.3.1 (test)]
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution enforce-plugin-versions of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve following dependencies: [maven-plugins:maven-cobertura-plugin:plugin:1.3 (test), maven-plugins:maven-findbugs-plugin:plugin:1.3.1 (test)]
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
... 20 more
Caused by: java.lang.RuntimeException: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve following dependencies: [maven-plugins:maven-cobertura-plugin:plugin:1.3 (test), maven-plugins:maven-findbugs-plugin:plugin:1.3.1 (test)]
at org.apache.maven.plugins.enforcer.BanCircularDependencies.getDependenciesToCheck(BanCircularDependencies.java:143)
at org.apache.maven.plugins.enforcer.BanCircularDependencies.execute(BanCircularDependencies.java:83)
at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:194)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
... 21 more
Caused by: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve following dependencies: [maven-plugins:maven-cobertura-plugin:plugin:1.3 (test), maven-plugins:maven-findbugs-plugin:plugin:1.3.1 (test)]
at org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder.resolveDependencies(Maven31DependencyGraphBuilder.java:133)
at org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder.buildDependencyGraph(Maven31DependencyGraphBuilder.java:113)
at org.apache.maven.shared.dependency.graph.internal.DefaultDependencyGraphBuilder.buildDependencyGraph(DefaultDependencyGraphBuilder.java:91)
at org.apache.maven.shared.dependency.graph.internal.DefaultDependencyGraphBuilder.buildDependencyGraph(DefaultDependencyGraphBuilder.java:66)
at org.apache.maven.plugins.enforcer.BanCircularDependencies.getDependenciesToCheck(BanCircularDependencies.java:137)
... 24 more
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project *:jar:1.10.0-b01-SNAPSHOT: The following artifacts could not be resolved: maven-plugins:maven-cobertura-plugin:plugin:1.3, maven-plugins:maven-findbugs-plugin:plugin:1.3.1: Failure to find maven-plugins:maven-cobertura-plugin:plugin:1.3 in * was cached in the local repository, resolution will not be reattempted until the update interval of nexus.public has elapsed or updates are forced
at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
at org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder.resolveDependencies(Maven31DependencyGraphBuilder.java:127)
... 28 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: maven-plugins:maven-cobertura-plugin:plugin:1.3, maven-plugins:maven-findbugs-plugin:plugin:1.3.1: Failure to find maven-plugins:maven-cobertura-plugin:plugin:1.3 in http://*/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus.public has elapsed or updates are forced
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
... 29 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: maven-plugins:maven-cobertura-plugin:plugin:1.3, maven-plugins:maven-findbugs-plugin:plugin:1.3.1: Failure to find maven-plugins:maven-cobertura-plugin:plugin:1.3 in http://*/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus.public has elapsed or updates are forced
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
... 30 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find maven-plugins:maven-cobertura-plugin:plugin:1.3 in * was cached in the local repository, resolution will not be reattempted until the update interval of nexus.public has elapsed or updates are forced
at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
... 32 more
```

---

**Affects:** 3.0.0-M2

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Every enforcer rule is responsible for its own logging, and it looks like here's a rule that's too verbose and probably should have gone for debug-logging instead of info-logging.
However, when running this with debug-logging( `mvn -X` or `mvn --debug`, you will see per rule when the execution starts and stops, and that's the correct level to show it.
