### ISSUE TITLE
[MENFORCER-9] Exception in java rule when using Apple JDK 6 Developer Preview

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-enforcer#507]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MENFORCER-9](https://issues.apache.org/jira/browse/MENFORCER-9?redirect=false)** and commented

[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] For input string: ""
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
at java.lang.Integer.parseInt(Integer.java:468)
at java.lang.Integer.parseInt(Integer.java:497)
at org.apache.maven.plugin.enforcer.RequireJavaVersion.normalizeJDKVersion(RequireJavaVersion.java:87)
at org.apache.maven.plugin.enforcer.RequireJavaVersion.execute(RequireJavaVersion.java:53)
at org.apache.maven.plugin.enforcer.EnforceMojo.execute(EnforceMojo.java:143)
at org.apache.maven.plugin.enforcer.EnforceOnceMojo.execute(EnforceOnceMojo.java:39)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:589)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 1.0-alpha-2

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Brett, can you paste the output from mvn --version using 2.0.7? This uses the same code to read the variables (plexus-utils os.java) and I'll be able to write a test around it.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Maven version: 2.0.7
Java version: 1.6.0-dp
OS name: "mac os x" version: "10.4.9" arch: "i386"

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

all set now
