### ISSUE TITLE
[MENFORCER-224] Regression from 1.3.1 to 1.4 with bannedDependencies rule

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-enforcer#722]
**[Henning Schmiedehausen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henning)** opened **[MENFORCER-224](https://issues.apache.org/jira/browse/MENFORCER-224?redirect=false)** and commented

the attached pom, when running "mvn enforcer:enforce" in the project will work with the enforcer plugin 1.3.1 but fail with the enforcer plugin 1.4 with

[,4\.11)
^
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce failed: Unclosed character class near index 7
[,4\.11)
^
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 19 more
Caused by: java.util.regex.PatternSyntaxException: Unclosed character class near index 7
[,4\.11)
^
at java.util.regex.Pattern.error(Pattern.java:1924)
at java.util.regex.Pattern.clazz(Pattern.java:2493)
at java.util.regex.Pattern.sequence(Pattern.java:2030)
at java.util.regex.Pattern.expr(Pattern.java:1964)
at java.util.regex.Pattern.compile(Pattern.java:1665)
at java.util.regex.Pattern.\<init>(Pattern.java:1337)
at java.util.regex.Pattern.compile(Pattern.java:1022)
at java.util.regex.Pattern.matches(Pattern.java:1128)
at org.apache.maven.plugins.enforcer.utils.ArtifactMatcher$Pattern.matches(ArtifactMatcher.java:148)
at org.apache.maven.plugins.enforcer.utils.ArtifactMatcher$Pattern.match(ArtifactMatcher.java:113)
at org.apache.maven.plugins.enforcer.BannedDependencies.compareDependency(BannedDependencies.java:149)
at org.apache.maven.plugins.enforcer.BannedDependencies.checkDependencies(BannedDependencies.java:117)
at org.apache.maven.plugins.enforcer.BannedDependencies.checkDependencies(BannedDependencies.java:76)
at org.apache.maven.plugins.enforcer.AbstractBanDependencies.execute(AbstractBanDependencies.java:94)
at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:150)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
... 20 more

Mostly because the version inclusion / exclusion expressions are not regexps.

---

**Affects:** 1.4

**Attachments:**
- [ArtifactMatcher.patch](https://issues.apache.org/jira/secure/attachment/12716461/ArtifactMatcher.patch) (_8.98 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12716520/pom.xml) (_1.19 kB_)

**Comment by jira-importer** [comment]
**[Brian Jackson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jaxzin)** commented

This just bit me too.  Any workaround?

**Comment by jira-importer** [comment]
**[Brian Jackson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jaxzin)** commented

I've attached a patch that fixes this issue. It includes integration tests to validate the fix.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Fixed in [r1662085](http://svn.apache.org/r1662085)
Patch of Brian Jackson applied.
Thanks for the patch and fixing the problem.

**Comment by jira-importer** [comment]
**[Henning Schmiedehausen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henning)** commented

open for four months now. Any ETA for a release?

**Comment by jira-importer** [comment]
**[Jason Dillon](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdillon)** commented

Still no release?
