### ISSUE TITLE
[MENFORCER-314] DependencyConvergence fails sporadically with a null message

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-enforcer#794]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** opened **[MENFORCER-314](https://issues.apache.org/jira/browse/MENFORCER-314?redirect=false)** and commented

Our Jenkins builds fail sporadically without providing a message:

```
17:08:28 [WARNING] Rule 4: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
17:08:28 null
```

Looking at the code, I suspect that this can happen [on line 132 of the rule](https://github.com/apache/maven-enforcer/blob/enforcer-3.0.0-M2/enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/DependencyConvergence.java#L132) when some underlying exception is caught which itself does not provide a (localized) message.
As the plugin [does not include the cause](https://github.com/apache/maven-enforcer/blob/enforcer-3.0.0-M2/maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java#L212) (unless `failFast` is set), you will just see a null message.

---

**Affects:** 1.4.1, 3.0.0-M1

**Remote Links:**
- [GitHub Pull Request #43
](https://github.com/apache/maven-enforcer/pull/43)
- [GitHub Pull Request #44
](https://github.com/apache/maven-enforcer/pull/44)

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

I've sent to PRs to improve output for such a case to figure out what is going on.

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise) Any chance to have one of the PRs integrated into 3.0.0? :)

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

After running some weeks with a custom build of the plugin incorporating PR #44, the problem finally struck and the output now reveals the underlying cause:

```
11:13:47 [WARNING] Rule 4: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
11:13:47 org.apache.maven.enforcer.rule.api.EnforcerRuleException
11:13:47 	at org.apache.maven.plugins.enforcer.DependencyConvergence.execute(DependencyConvergence.java:132)
11:13:47 	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:204)
11:13:47 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
11:13:47 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
11:13:47 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
11:13:47 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
11:13:47 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
11:13:47 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
11:13:47 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
11:13:47 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:13:47 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11:13:47 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:13:47 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:13:47 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:13:47 	at java.lang.Thread.run(Thread.java:748)
11:13:47 Caused by: java.lang.NullPointerException
11:13:47 	at java.util.Hashtable.put(Hashtable.java:460)
11:13:47 	at org.apache.maven.properties.internal.SystemProperties.addSystemProperties(SystemProperties.java:38)
11:13:47 	at org.apache.maven.project.artifact.MavenMetadataSource.getSystemProperties(MavenMetadataSource.java:756)
11:13:47 	at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:574)
11:13:47 	at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:190)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:532)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:144)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:100)
11:13:47 	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:782)
11:13:47 	at org.apache.maven.shared.dependency.tree.DefaultDependencyTreeBuilder.buildDependencyTree(DefaultDependencyTreeBuilder.java:118)
11:13:47 	at org.apache.maven.plugins.enforcer.DependencyConvergence.getNode(DependencyConvergence.java:86)
11:13:47 	at org.apache.maven.plugins.enforcer.DependencyConvergence.execute(DependencyConvergence.java:114)
11:13:47 	... 14 more
```

So in this case it was MNG-6105 (we are still on Maven 3.3.9).

**Comment by jira-importer** [comment]
**[Enrico Olivelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli)** commented

committed as 9bf2bac4447a7663cf26defb957610a6d9bd28eb
